// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYBIFEFeCbZSZSaqzo-IBKcVFfl3YgP-E',
    appId: '1:123412677445:web:538e21ae1ddff86739b42c',
    messagingSenderId: '123412677445',
    projectId: 'swift-pool-de70a',
    authDomain: 'swift-pool-de70a.firebaseapp.com',
    storageBucket: 'swift-pool-de70a.firebasestorage.app',
    measurementId: 'G-JR7F6P4GG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4VwejT56s2Xs1aC1EdMlABa8ZHrB_UjQ',
    appId: '1:123412677445:android:ce1bd68348c0a13939b42c',
    messagingSenderId: '123412677445',
    projectId: 'swift-pool-de70a',
    storageBucket: 'swift-pool-de70a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHGiJAhjEDH5sU8JoNFnuRP7hRB8IwD58',
    appId: '1:123412677445:ios:58908546239fa61139b42c',
    messagingSenderId: '123412677445',
    projectId: 'swift-pool-de70a',
    storageBucket: 'swift-pool-de70a.firebasestorage.app',
    iosBundleId: 'com.example.swift2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHGiJAhjEDH5sU8JoNFnuRP7hRB8IwD58',
    appId: '1:123412677445:ios:58908546239fa61139b42c',
    messagingSenderId: '123412677445',
    projectId: 'swift-pool-de70a',
    storageBucket: 'swift-pool-de70a.firebasestorage.app',
    iosBundleId: 'com.example.swift2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYBIFEFeCbZSZSaqzo-IBKcVFfl3YgP-E',
    appId: '1:123412677445:web:00d65bd6231b89e339b42c',
    messagingSenderId: '123412677445',
    projectId: 'swift-pool-de70a',
    authDomain: 'swift-pool-de70a.firebaseapp.com',
    storageBucket: 'swift-pool-de70a.firebasestorage.app',
    measurementId: 'G-XNNXN7KSNK',
  );
}
